using UnityEditor;

namespace JeffGrawAssets.FlexibleUI
{
public class ProceduralPropertiesEditor
{
    public readonly int AnimationStateIdx, AnimationStateSubIdx;
    public readonly ProceduralProperties ProceduralProperties;
    public readonly SerializedProperty BaseSerializedProperty;

    public SerializedProperty uvRectProperty;
    public SerializedProperty uvRectXProperty;
    public SerializedProperty uvRectYProperty;
    public SerializedProperty uvRectZProperty;
    public SerializedProperty uvRectWProperty;
    public SerializedProperty primaryColorFadeProperty;
    public SerializedProperty cornerChamferProperty;
    public SerializedProperty cornerXChamferProperty;
    public SerializedProperty cornerYChamferProperty;
    public SerializedProperty cornerZChamferProperty;
    public SerializedProperty cornerWChamferProperty;
    public SerializedProperty collapsedCornerChamferProperty;
    public SerializedProperty cornerConcavityProperty;
    public SerializedProperty cornerXConcavityProperty;
    public SerializedProperty cornerYConcavityProperty;
    public SerializedProperty cornerZConcavityProperty;
    public SerializedProperty cornerWConcavityProperty;
    public SerializedProperty collapsedCornerConcavityProperty;
    public SerializedProperty collapseEdgeAmountProperty;
    public SerializedProperty collapseEdgeAmountAbsoluteProperty;
    public SerializedProperty collapseEdgePositionProperty;
    public SerializedProperty strokeProperty;
    public SerializedProperty softnessProperty;
    public SerializedProperty sizeModifierProperty;
    public SerializedProperty sizeModifierXProperty;
    public SerializedProperty sizeModifierYProperty;
    public SerializedProperty offsetProperty;
    public SerializedProperty offsetXProperty;
    public SerializedProperty offsetYProperty;
    public SerializedProperty rotationProperty;
    public SerializedProperty simpleCutoutXProperty;
    public SerializedProperty simpleCutoutYProperty;
    public SerializedProperty simpleCutoutZProperty;
    public SerializedProperty simpleCutoutWProperty;
    public SerializedProperty sdfCutoutChamferProperty;
    public SerializedProperty sdfCutoutChamferXProperty;
    public SerializedProperty sdfCutoutChamferYProperty;
    public SerializedProperty sdfCutoutChamferZProperty;
    public SerializedProperty sdfCutoutChamferWProperty;
    public SerializedProperty sdfCutoutConcavityProperty;
    public SerializedProperty sdfCutoutConcavityXProperty;
    public SerializedProperty sdfCutoutConcavityYProperty;
    public SerializedProperty sdfCutoutConcavityZProperty;
    public SerializedProperty sdfCutoutConcavityWProperty;
    public SerializedProperty sdfCutoutPositionProperty;
    public SerializedProperty sdfCutoutSizeProperty;
    public SerializedProperty sdfCutoutRotationProperty;
    public SerializedProperty outlineWidthProperty;
    public SerializedProperty proceduralGradientPositionProperty;
    public SerializedProperty radialGradientSizeProperty;
    public SerializedProperty radialGradientStrengthProperty;
    public SerializedProperty angleGradientStrengthProperty;
    public SerializedProperty proceduralGradientAngleProperty;
    public SerializedProperty sdfGradientInnerDistanceProperty;
    public SerializedProperty sdfGradientOuterDistanceProperty;
    public SerializedProperty sdfGradientInnerReachProperty;
    public SerializedProperty sdfGradientOuterReachProperty;
    public SerializedProperty conicalGradientCurvatureProperty;
    public SerializedProperty conicalGradientTailStrengthProperty;
    public SerializedProperty noiseScaleProperty;
    public SerializedProperty noiseSeedProperty;
    public SerializedProperty noiseEdgeProperty;
    public SerializedProperty noiseStrengthProperty;
    public SerializedProperty proceduralGradientPointerStrengthProperty;
    public SerializedProperty patternDensityProperty;
    public SerializedProperty patternSpeedProperty;
    public SerializedProperty patternCellParamProperty;
    public SerializedProperty patternLineThicknessProperty;
    public SerializedProperty patternSpriteRotationProperty;
    public SerializedProperty primaryColorsProperty;
    public SerializedProperty primaryColorOffsetProperty;
    public SerializedProperty primaryColorRotationProperty;
    public SerializedProperty primaryColorScaleProperty;
    public SerializedProperty outlineColorsProperty;
    public SerializedProperty outlineColorOffsetProperty;
    public SerializedProperty outlineColorRotationProperty;
    public SerializedProperty outlineColorScaleProperty;
    public SerializedProperty proceduralGradientColorsProperty;
    public SerializedProperty proceduralGradientColorOffsetProperty;
    public SerializedProperty proceduralGradientColorRotationProperty;
    public SerializedProperty proceduralGradientColorScaleProperty;
    public SerializedProperty patternColorsProperty;
    public SerializedProperty patternColorOffsetProperty;
    public SerializedProperty patternColorRotationProperty;
    public SerializedProperty patternColorScaleProperty;

    public ProceduralPropertiesEditor(ProceduralAnimationState[] animationStatesList, SerializedProperty parentProp, int animationStateIdx, int animationStateSubIdx)
    {
        (AnimationStateIdx, AnimationStateSubIdx) = (animationStateIdx, animationStateSubIdx);
        ProceduralProperties = animationStatesList[animationStateIdx].proceduralProperties[animationStateSubIdx];
        BaseSerializedProperty = parentProp.FindPropertyRelative(nameof(QuadData.proceduralAnimationStates)).GetArrayElementAtIndex(AnimationStateIdx).FindPropertyRelative(nameof(ProceduralAnimationState.proceduralProperties)).GetArrayElementAtIndex(AnimationStateSubIdx);
        uvRectProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.uvRect));
        uvRectXProperty = uvRectProperty.FindPropertyRelative("x");
        uvRectYProperty = uvRectProperty.FindPropertyRelative("y");
        uvRectZProperty = uvRectProperty.FindPropertyRelative("z");
        uvRectWProperty = uvRectProperty.FindPropertyRelative("w");
        primaryColorFadeProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorFade));
        cornerChamferProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.cornerChamfer));
        cornerXChamferProperty = cornerChamferProperty.FindPropertyRelative("x");
        cornerYChamferProperty = cornerChamferProperty.FindPropertyRelative("y");
        cornerZChamferProperty = cornerChamferProperty.FindPropertyRelative("z");
        cornerWChamferProperty = cornerChamferProperty.FindPropertyRelative("w");
        cornerConcavityProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.cornerConcavity));
        cornerXConcavityProperty = cornerConcavityProperty.FindPropertyRelative("x");
        cornerYConcavityProperty = cornerConcavityProperty.FindPropertyRelative("y");
        cornerZConcavityProperty = cornerConcavityProperty.FindPropertyRelative("z");
        cornerWConcavityProperty = cornerConcavityProperty.FindPropertyRelative("w");
        softnessProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.softness));
        offsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.offset));
        offsetXProperty = offsetProperty.FindPropertyRelative("x");
        offsetYProperty = offsetProperty.FindPropertyRelative("y");
        sizeModifierProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.sizeModifier));
        sizeModifierXProperty = sizeModifierProperty.FindPropertyRelative("x");
        sizeModifierYProperty = sizeModifierProperty.FindPropertyRelative("y");
        rotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.rotation));
        primaryColorsProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColors));
        primaryColorOffsetProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorOffset));
        primaryColorRotationProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorRotation));
        primaryColorScaleProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.primaryColorScale));

        var outlineAnimProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.outlineAnim));
        outlineWidthProperty = outlineAnimProperty?.FindPropertyRelative(nameof(OutlineAnimData.outlineWidth));
        outlineColorsProperty = outlineAnimProperty?.FindPropertyRelative(nameof(OutlineAnimData.outlineColors));
        outlineColorOffsetProperty = outlineAnimProperty?.FindPropertyRelative(nameof(OutlineAnimData.outlineColorOffset));
        outlineColorRotationProperty = outlineAnimProperty?.FindPropertyRelative(nameof(OutlineAnimData.outlineColorRotation));
        outlineColorScaleProperty = outlineAnimProperty?.FindPropertyRelative(nameof(OutlineAnimData.outlineColorScale));

        var gradientAnimProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.gradientAnim));
        proceduralGradientPositionProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientPosition));
        radialGradientSizeProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.radialGradientSize));
        radialGradientStrengthProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.radialGradientStrength));
        angleGradientStrengthProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.angleGradientStrength));
        proceduralGradientAngleProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientAngle));
        sdfGradientInnerDistanceProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.sdfGradientInnerDistance));
        sdfGradientOuterDistanceProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.sdfGradientOuterDistance));
        sdfGradientInnerReachProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.sdfGradientInnerReach));
        sdfGradientOuterReachProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.sdfGradientOuterReach));
        conicalGradientCurvatureProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.conicalGradientCurvature));
        conicalGradientTailStrengthProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.conicalGradientTailStrength));
        noiseScaleProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.noiseScale));
        noiseSeedProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.noiseSeed));
        noiseEdgeProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.noiseEdge));
        noiseStrengthProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.noiseStrength));
        proceduralGradientPointerStrengthProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientPointerStrength));
        proceduralGradientColorsProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientColors));
        proceduralGradientColorOffsetProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientColorOffset));
        proceduralGradientColorRotationProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientColorRotation));
        proceduralGradientColorScaleProperty = gradientAnimProperty?.FindPropertyRelative(nameof(GradientAnimData.proceduralGradientColorScale));

        var patternAnimProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.patternAnim));
        patternDensityProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternDensity));
        patternSpeedProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternSpeed));
        patternCellParamProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternCellParam));
        patternLineThicknessProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternLineThickness));
        patternSpriteRotationProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternSpriteRotation));
        patternColorsProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternColors));
        patternColorOffsetProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternColorOffset));
        patternColorRotationProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternColorRotation));
        patternColorScaleProperty = patternAnimProperty?.FindPropertyRelative(nameof(PatternAnimData.patternColorScale));

        var cutoutAnimProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.cutoutAnim));
        var simpleCutoutProperty = cutoutAnimProperty?.FindPropertyRelative(nameof(CutoutAnimData.simpleCutout));
        simpleCutoutXProperty = simpleCutoutProperty?.FindPropertyRelative("x");
        simpleCutoutYProperty = simpleCutoutProperty?.FindPropertyRelative("y");
        simpleCutoutZProperty = simpleCutoutProperty?.FindPropertyRelative("z");
        simpleCutoutWProperty = simpleCutoutProperty?.FindPropertyRelative("w");
        sdfCutoutChamferProperty = cutoutAnimProperty?.FindPropertyRelative(nameof(CutoutAnimData.sdfCutoutChamfer));
        sdfCutoutChamferXProperty = sdfCutoutChamferProperty?.FindPropertyRelative("x");
        sdfCutoutChamferYProperty = sdfCutoutChamferProperty?.FindPropertyRelative("y");
        sdfCutoutChamferZProperty = sdfCutoutChamferProperty?.FindPropertyRelative("z");
        sdfCutoutChamferWProperty = sdfCutoutChamferProperty?.FindPropertyRelative("w");
        sdfCutoutConcavityProperty = cutoutAnimProperty?.FindPropertyRelative(nameof(CutoutAnimData.sdfCutoutConcavity));
        sdfCutoutConcavityXProperty = sdfCutoutConcavityProperty?.FindPropertyRelative("x");
        sdfCutoutConcavityYProperty = sdfCutoutConcavityProperty?.FindPropertyRelative("y");
        sdfCutoutConcavityZProperty = sdfCutoutConcavityProperty?.FindPropertyRelative("z");
        sdfCutoutConcavityWProperty = sdfCutoutConcavityProperty?.FindPropertyRelative("w");
        sdfCutoutPositionProperty = cutoutAnimProperty?.FindPropertyRelative(nameof(CutoutAnimData.sdfCutoutPosition));
        sdfCutoutSizeProperty = cutoutAnimProperty?.FindPropertyRelative(nameof(CutoutAnimData.sdfCutoutSize));
        sdfCutoutRotationProperty = cutoutAnimProperty?.FindPropertyRelative(nameof(CutoutAnimData.sdfCutoutRotation));

        var strokeAnimProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.strokeAnim));
        strokeProperty = strokeAnimProperty?.FindPropertyRelative(nameof(StrokeAnimData.stroke));

        var skewAnimProperty = BaseSerializedProperty.FindPropertyRelative(nameof(ProceduralProperties.skewAnim));
        collapsedCornerChamferProperty = skewAnimProperty?.FindPropertyRelative(nameof(SkewAnimData.collapsedCornerChamfer));
        collapsedCornerConcavityProperty = skewAnimProperty?.FindPropertyRelative(nameof(SkewAnimData.collapsedCornerConcavity));
        collapseEdgeAmountProperty = skewAnimProperty?.FindPropertyRelative(nameof(SkewAnimData.collapseEdgeAmount));
        collapseEdgeAmountAbsoluteProperty = skewAnimProperty?.FindPropertyRelative(nameof(SkewAnimData.collapseEdgeAmountAbsolute));
        collapseEdgePositionProperty = skewAnimProperty?.FindPropertyRelative(nameof(SkewAnimData.collapseEdgePosition));
    }
}
}
